// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSWEB.Server.Context;

#nullable disable

namespace POSWEB.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POSWEB.Server.Entitites.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomBarcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinishedGoods")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRawMaterial")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<short>("ProductCategoryCategoryId")
                        .HasColumnType("smallint");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("ProductUnitUnitId")
                        .HasColumnType("smallint");

                    b.Property<int>("ProductsCreated")
                        .HasColumnType("int");

                    b.Property<int?>("ProductsUpdated")
                        .HasColumnType("int");

                    b.Property<decimal?>("PurchaseRate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long?>("ReOrederLevel")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SellingRate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("VatPercent")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal?>("WholesalePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCategoryCategoryId");

                    b.HasIndex("ProductUnitUnitId");

                    b.HasIndex("ProductsCreated");

                    b.HasIndex("ProductsUpdated");

                    b.ToTable("Products", "product");
                });

            modelBuilder.Entity("POSWEB.Server.Entitites.ProductCategory", b =>
                {
                    b.Property<short>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductCategoriesCreated")
                        .HasColumnType("int");

                    b.Property<int?>("ProductCategoriesUpdated")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("ProductCategoriesCreated");

                    b.HasIndex("ProductCategoriesUpdated");

                    b.ToTable("ProductCategories", "product");
                });

            modelBuilder.Entity("POSWEB.Server.Entitites.ProductUnit", b =>
                {
                    b.Property<short>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("UnitId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.ToTable("ProductUnits", "lookup");
                });

            modelBuilder.Entity("POSWEB.Server.Entitites.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users", "user");
                });

            modelBuilder.Entity("POSWEB.Server.Entitites.Product", b =>
                {
                    b.HasOne("POSWEB.Server.Entitites.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POSWEB.Server.Entitites.ProductUnit", "ProductUnit")
                        .WithMany("Products")
                        .HasForeignKey("ProductUnitUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POSWEB.Server.Entitites.User", "CreatedBy")
                        .WithMany("ProductsCreated")
                        .HasForeignKey("ProductsCreated")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POSWEB.Server.Entitites.User", "LastUpdatedBy")
                        .WithMany("ProductsUpdated")
                        .HasForeignKey("ProductsUpdated")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductUnit");
                });

            modelBuilder.Entity("POSWEB.Server.Entitites.ProductCategory", b =>
                {
                    b.HasOne("POSWEB.Server.Entitites.User", "CreatedBy")
                        .WithMany("ProductCategoriesCreated")
                        .HasForeignKey("ProductCategoriesCreated")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POSWEB.Server.Entitites.User", "LastUpdatedBy")
                        .WithMany("ProductCategoriesUpdated")
                        .HasForeignKey("ProductCategoriesUpdated")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");
                });

            modelBuilder.Entity("POSWEB.Server.Entitites.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("POSWEB.Server.Entitites.ProductUnit", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("POSWEB.Server.Entitites.User", b =>
                {
                    b.Navigation("ProductCategoriesCreated");

                    b.Navigation("ProductCategoriesUpdated");

                    b.Navigation("ProductsCreated");

                    b.Navigation("ProductsUpdated");
                });
#pragma warning restore 612, 618
        }
    }
}
