global using Application.Contractors;
global using Application.ReponseDTO;
global using Application.RequestDTO;
global using Domain.Entitites;
global using System.Linq.Expressions;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Reflection;
global using Application.Contractors.Common;